### ISSUE TITLE
Support for auth token in CLI and http POST request

### ISSUE THREAD

**Issue by GalaxyGorilla** [stritzinger/sscg_generator#4]

**Comment by matlaj** [comment]
Here is how I think this should work, based on how the management module works right now. @GalaxyGorilla ?

The CLI takes in a new param, `token`, and adds it to the payload when publishing the SBOM and the SSCG. The token should be under the key `token`, so: `{sbom: <SBOM>, sscg: <SSCG>, token: <TOKEN>}`.

The CLI should gracefully handle an error response.

**Comment by IciaCarroBarallobre** [comment]
Token is mandatory?

**Comment by matlaj** [comment]
Yeah
