### ISSUE TITLE
Crash on a successful http request

### ISSUE THREAD

**Issue by matlaj** [stritzinger/sscg_generator#6]
When a HTTP request is successful, the module `sscg_generator_http` returns just the atom `ok`:
https://github.com/stritzinger/sscg_generator/blob/e480fab7a46b1dc4c9eaf0bcd5c0f223f4d18d86/src/sscg_generator_http.erl#L71-L73

But the module `sscg_generator_publish` expects a tuple:
https://github.com/stritzinger/sscg_generator/blob/e480fab7a46b1dc4c9eaf0bcd5c0f223f4d18d86/src/sscg_generator_publish.erl#L60-L61

...causing a crash on a success response:
```
escript: exception error: no case clause matching ok
  in function  sscg_generator_publish:publish/1 (/root/.sscg_generator/src/sscg_generator_publish.erl, line 60)
  in call from sscg_generator:main/1 (/root/.sscg_generator/src/sscg_generator.erl, line 23)
  in call from escript:run/2 (escript.erl, line 904)
  in call from escript:start/1 (escript.erl, line 418)
  in call from init:start_it/1 
  in call from init:start_em/1 
  in call from init:do_boot/3 
```

`sscg_generator` should not crash on a success response.

**Comment by IciaCarroBarallobre** [comment]
Ups :0 no idea how I tested this, thxs for the debugging
